backend:
  name: git-gateway
  branch: main  # ou 'master' selon ta branche par défaut

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Page d’accueil"
    files:
      - file: "src/content/home/index.md"
        label: "Contenu de la page d’accueil"
        name: "home"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - label: "Blocs"
            name: "blocks"
            widget: list
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Svg", name: "svg", widget: "image" }
              - { label: "Texte", name: "text", widget: "text" }
              - { label: "Couleur", name: "color", widget: "text" }
              - { label: "Lignes", name: "lines", widget: "number" }
